name: random_people_fluttering
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Prompt
      fonts:
        - asset: ./assets/fonts/Prompt-Bold.ttf
          weight: 700
        - asset: ./assets/fonts/Prompt-SemiBold.ttf
          weight: 600
    - family: Jost
      fonts:
        - asset: ./assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: ./assets/fonts/Jost-Medium.ttf
          weight: 500
